# Generated by Django 5.1.1 on 2024-11-08 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "category_id",
                    models.IntegerField(
                        choices=[
                            (0, "분식"),
                            (1, "양식"),
                            (2, "중식"),
                            (3, "한식"),
                            (4, "일식"),
                        ],
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("allergy_name", models.CharField(max_length=50)),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="account.useraccount",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_account", "allergy_name")},
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("is_vegan", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "남성"), ("F", "여성")], max_length=1
                    ),
                ),
                ("random_name", models.BooleanField(default=False)),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_info",
                        to="account.useraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnpreferredFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("food_name", models.CharField(max_length=100)),
                (
                    "allergy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.allergy",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.foodcategory",
                    ),
                ),
                (
                    "user_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unpreferred_foods",
                        to="account.userinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreferredFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("food_name", models.CharField(max_length=100)),
                (
                    "allergy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.allergy",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.foodcategory",
                    ),
                ),
                (
                    "user_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_foods",
                        to="account.userinfo",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserAllergy",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
