# Generated by Django 5.1.3 on 2024-11-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferredfood',
            name='food_number',
            field=models.IntegerField(null=True),
        ),
    ]
