# Generated by Django 5.1.3 on 2024-11-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_preferredfood_food_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='unpreferredfood',
            name='food_number',
            field=models.IntegerField(null=True),
        ),
    ]
