# Generated by Django 5.1.3 on 2024-11-30 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_nutritionalinformation_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vegan', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1)),
                ('allergies', models.TextField(blank=True)),
                ('preferred_foods', models.TextField(blank=True)),
                ('unpreferred_foods', models.TextField(blank=True)),
                ('dwell_times', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='account.useraccount')),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
            },
        ),
    ]
